### ISSUE TITLE
Command line script using this API

### ISSUE THREAD

**Issue by Naereen** [EmilioK97/pydeepl#3]
Hi,
You could be interested of [this script, `deepl.py`](https://bitbucket.org/lbesson/bin/src/master/deepl.py), that I just wrote: it uses your API to translate a line of text given from the command line or a small text file. Examples:
![test deepl py](https://user-images.githubusercontent.com/11994719/33839978-eeb229fc-de93-11e7-9e98-45c65ac4c984.png)

Maybe you would like to include it (feel free to modify as you wish) or add something like this in your project.

It could be good if the `pydeepl` module was actually executable, so
```bash
python -m pydeepl
```
would behave like my script?

**Comment by EmilioK97** [comment]
I'll check It this week asap.

El 11 dic. 2017 4:54 p. m., Lilian Besson <notifications@github.com> escribió:

Hi,
You could be interested of this script, deepl.py<https://bitbucket.org/lbesson/bin/src/master/deepl.py>, that I just wrote: it uses your API to translate a line of text given from the command line or a small text file. Examples:
[test deepl py]<https://user-images.githubusercontent.com/11994719/33839978-eeb229fc-de93-11e7-9e98-45c65ac4c984.png>

Maybe you would like to include it (feel free to modify as you wish) or add something like this in your project.

It could be good if the pydeepl module was actually executable, so

python -m pydeepl

would behave like my script?

**Comment by Naereen** [comment]
Just relaunching

**Comment by Naereen** [comment]
@EmilioK97 interesting in merging my script into your project?
It could be easy to add a flag in the install process of your `setup.py`, to let any one who installs `pydeepl` benefit from a cli client?

**Comment by EmilioK97** [comment]
I'll check it again. I was so busy I forgot about it at all. I added it to my todo list. Sorry for the no reply.

**Comment by Naereen** [comment]
No problem, we're all so busy I understand!

**Comment by EmilioK97** [comment]
Commit: e11c5a5f9f4da5ab387f70a2f12c2e731fbfbef8

**Comment by Naereen** [comment]
Hi @EmilioK97, great!

I am curious about one detail: so far my script is hard-coded to do French-English by default, but it's a very specific choice for my usage.
Could we use at `LANG` or `LANGUAGE` (environment variable) or other indicators of the user's language, to automatically set the default translation target?

**Comment by EmilioK97** [comment]
It can be done in case you no specify the target language. I have no time right now, maybe later this week. If you want to implement it feel free to make a pull request.

**Comment by Naereen** [comment]
I'm running out of time too sorry!
